import { defineConfig } from "drizzle-kit";

export default defineConfig({
  dialect: "postgresql",
  // Catalog tables + Better Auth tables (generated by `npm run auth:generate`).
  schema: ["./src/db/schema.ts", "./src/db/auth-schema.ts"],
  out: "./drizzle",
  dbCredentials: { url: process.env.DATABASE_URL! },
  strict: true,
});
